name: Build Tiny11 ISO

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build type'
        required: true
        default: 'maker'
        type: choice
        options:
          - maker
          - core
      iso_url:
        description: 'Windows ISO URL (optional, defaults to Windows 11 25H2 if not provided)'
        required: false
        default: 'https://software-static.download.prss.microsoft.com/dbazure/888969d5-f34g-4e03-ac9d-1f9786c66749/26200.6584.250915-1905.25h2_ge_release_svc_refresh_CLIENT_CONSUMER_x64FRE_en-us.iso'
        type: string
      remove_defender:
        description: '⚠️ MAKER ONLY: Remove Windows Defender (default: no)'
        required: false
        default: 'no'
        type: choice
        options:
          - yes
          - no
      remove_ai:
        description: '⚠️ MAKER ONLY: Remove AI/Copilot components (default: yes)'
        required: false
        default: 'yes'
        type: choice
        options:
          - yes
          - no
      remove_edge:
        description: '⚠️ MAKER ONLY: Remove Microsoft Edge (default: yes)'
        required: false
        default: 'yes'
        type: choice
        options:
          - yes
          - no
      remove_store:
        description: '⚠️ MAKER ONLY: Remove Microsoft Store (default: yes)'
        required: false
        default: 'yes'
        type: choice
        options:
          - yes
          - no
  push:
    branches:
      - main
    paths:
      - '*.ps1'
      - '.github/workflows/*.yml'
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 180
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup PowerShell
        shell: pwsh
        run: |
          $PSVersionTable
          Write-Host "PowerShell version: $($PSVersionTable.PSVersion)"
          
      - name: Download and Mount Windows ISO
        shell: pwsh
        env:
          ISO_URL_SECRET: ${{ secrets.ISO_URL }}
          ISO_URL_INPUT: ${{ github.event.inputs.iso_url }}
          DEFAULT_ISO_URL: 'https://software-static.download.prss.microsoft.com/dbazure/888969d5-f34g-4e03-ac9d-1f9786c66749/26200.6584.250915-1905.25h2_ge_release_svc_refresh_CLIENT_CONSUMER_x64FRE_en-us.iso'
        run: |
          $ErrorActionPreference = 'Stop'
          
          # Determine ISO source
          # Priority: Input ISO_URL > Secret ISO_URL > Default URL
          $isoUrl = $null
          
          if ($env:ISO_URL_INPUT) {
            Write-Host "Using ISO URL from workflow input..."
            $isoUrl = $env:ISO_URL_INPUT
          } elseif ($env:ISO_URL_SECRET) {
            Write-Host "Using ISO URL from repository secret..."
            $isoUrl = $env:ISO_URL_SECRET
          } else {
            Write-Host "Using default Windows 11 ISO URL..."
            $isoUrl = $env:DEFAULT_ISO_URL
          }
          
          $isoFilePath = "$env:RUNNER_TEMP\windows.iso"
          
          Write-Host "Downloading Windows ISO from: $isoUrl"
          Write-Host "This may take a while depending on your connection speed..."
          
          try {
            Invoke-WebRequest -Uri $isoUrl -OutFile $isoFilePath -UseBasicParsing
            Write-Host "✓ ISO downloaded successfully" -ForegroundColor Green
          } catch {
            Write-Error "Failed to download ISO: $_"
            exit 1
          }
          
          # Verify ISO file exists
          if (-not (Test-Path $isoFilePath)) {
            Write-Error "ISO file not found at: $isoFilePath"
            exit 1
          }
          
          $isoSize = (Get-Item $isoFilePath).Length / 1GB
          Write-Host "Downloaded ISO size: $([math]::Round($isoSize, 2)) GB"
          
          Write-Host "Mounting ISO file: $isoFilePath"
          
          # Mount ISO and get drive letter
          try {
            $mountResult = Mount-DiskImage -ImagePath $isoFilePath -PassThru -ErrorAction Stop
            $volume = $mountResult | Get-Volume
            $isoDriveLetter = $volume.DriveLetter
            
            if ($isoDriveLetter) {
              $isoDrive = "$isoDriveLetter`:"
              Write-Host "✓ ISO mounted successfully to drive: $isoDrive" -ForegroundColor Green
              echo "ISO_DRIVE=$isoDrive" >> $env:GITHUB_ENV
              echo "ISO_FILE_PATH=$isoFilePath" >> $env:GITHUB_ENV
            } else {
              Write-Error "Failed to get drive letter from mounted ISO"
              exit 1
            }
          } catch {
            Write-Error "Failed to mount ISO: $_"
            exit 1
          }
          
      - name: Build Tiny11 ISO
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          
          # Get ISO drive from mounted ISO
          $isoDrive = $env:ISO_DRIVE
          if (-not $isoDrive) {
            Write-Error "ISO drive not set. Mount step may have failed."
            exit 1
          }
          
          # Scratch drive will use runner temp or current directory
          $scratchDrive = $PSScriptRoot
          
          Write-Host "Building Tiny11 ISO..."
          Write-Host "ISO Drive: $isoDrive"
          Write-Host "Scratch Drive: $scratchDrive"
          Write-Host "Build Type: ${{ github.event.inputs.build_type || 'maker' }}"
          
          # Build arguments
          $buildArgs = @()
          
          # Extract drive letter (remove colon)
          if ($isoDrive -match '^([A-Z]):$') {
            $buildArgs += '-ISO', $Matches[1]
          } else {
            Write-Error "Invalid ISO drive format: $isoDrive"
            exit 1
          }
          
          # Determine script to run
          $buildType = "${{ github.event.inputs.build_type || 'maker' }}"
          $scriptName = if ($buildType -eq 'core') { 'tiny11Coremaker.ps1' } else { 'tiny11maker.ps1' }
          
          # Add optional debloat parameters only for maker
          if ($buildType -eq 'maker') {
            Write-Host "Adding optional debloat parameters for maker..."
            
            # Get input values with defaults
            $removeDefender = if ('${{ github.event.inputs.remove_defender }}') { '${{ github.event.inputs.remove_defender }}' } else { 'no' }
            $removeAI = if ('${{ github.event.inputs.remove_ai }}') { '${{ github.event.inputs.remove_ai }}' } else { 'yes' }
            $removeEdge = if ('${{ github.event.inputs.remove_edge }}') { '${{ github.event.inputs.remove_edge }}' } else { 'yes' }
            $removeStore = if ('${{ github.event.inputs.remove_store }}') { '${{ github.event.inputs.remove_store }}' } else { 'yes' }
            
            $buildArgs += '-RemoveDefender', $removeDefender
            $buildArgs += '-RemoveAI', $removeAI
            $buildArgs += '-RemoveEdge', $removeEdge
            $buildArgs += '-RemoveStore', $removeStore
            
            Write-Host "Debloat options: Defender=$removeDefender, AI=$removeAI, Edge=$removeEdge, Store=$removeStore"
          } else {
            Write-Host "Core maker selected - optional debloat parameters ignored (core has fixed settings)"
          }
          
          Write-Host "Running: $scriptName"
          Write-Host "Arguments: $($buildArgs -join ' ')"
          
          # Run the builder script
          & ".\$scriptName" @buildArgs
          
          # Check if ISO was created
          $isoPath = Join-Path $PSScriptRoot "tiny11.iso"
          if (Test-Path $isoPath) {
            Write-Host "ISO created successfully: $isoPath"
            $isoSize = (Get-Item $isoPath).Length / 1GB
            Write-Host "ISO size: $([math]::Round($isoSize, 2)) GB"
          } else {
            Write-Error "ISO was not created at expected path: $isoPath"
            exit 1
          }
          
      - name: Upload ISO artifact
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: tiny11-iso-${{ github.event.inputs.build_type || 'maker' }}-${{ github.run_number }}
          path: |
            tiny11.iso
            *.log
          retention-days: 7
          compression-level: 0
          
      - name: Create Release
        if: github.event_name == 'release' && github.event.action == 'published'
        shell: pwsh
        run: |
          $isoPath = "tiny11.iso"
          if (Test-Path $isoPath) {
            Write-Host "Preparing release asset..."
            $isoSize = (Get-Item $isoPath).Length / 1GB
            Write-Host "ISO size: $([math]::Round($isoSize, 2)) GB"
            
            # Note: Actual release upload would be handled by release action
            # This step just prepares the file
          }
          
      - name: Cleanup
        if: always()
        shell: pwsh
        env:
          ISO_FILE_PATH: ${{ env.ISO_FILE_PATH }}
        run: |
          # Unmount ISO if we mounted it
          if ($env:ISO_FILE_PATH) {
            Write-Host "Unmounting ISO: $env:ISO_FILE_PATH"
            try {
              Get-DiskImage | Where-Object { $_.ImagePath -eq $env:ISO_FILE_PATH } | Dismount-DiskImage -ErrorAction Stop
              Write-Host "✓ ISO unmounted successfully" -ForegroundColor Green
            } catch {
              Write-Warning "Failed to unmount ISO: $_"
            }
            
            # Cleanup temporary ISO file if it was downloaded
            if ($env:ISO_FILE_PATH -like "*RUNNER_TEMP*") {
              Write-Host "Removing temporary ISO file..."
              Remove-Item -Path $env:ISO_FILE_PATH -Force -ErrorAction SilentlyContinue
            }
          }
