name: Build Tiny11 ISO

on:
  workflow_call:
    inputs:
      build_type:
        description: 'Build type'
        required: false
        default: 'maker'
        type: string
      iso_url:
        description: 'Windows ISO URL (leave empty to use default Windows 11 25H2 ISO)'
        required: false
        type: string
      version_selector:
        description: 'Windows edition to build (default: Auto - selects Pro)'
        required: false
        default: 'Auto'
        type: string
      remove_defender:
        description: 'Remove Windows Defender (applies to maker and core, default: false)'
        required: false
        default: 'false'
        type: string
      remove_ai:
        description: 'Remove AI/Copilot components (applies to maker and core, default: true)'
        required: false
        default: 'true'
        type: string
      remove_edge:
        description: 'Remove Microsoft Edge browser (applies to maker and core, default: true)'
        required: false
        default: 'true'
        type: string
      remove_store:
        description: 'Remove Microsoft Store (applies to maker and core, default: true)'
        required: false
        default: 'true'
        type: string
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build type'
        required: true
        default: 'maker'
        type: choice
        options:
          - maker
          - core
      iso_url:
        description: 'Windows ISO URL (leave empty to use default Windows 11 25H2 ISO)'
        required: false
        type: string
      version_selector:
        description: 'Windows edition to build (default: Auto - selects Pro)'
        required: false
        default: 'Auto'
        type: choice
        options:
          - Auto
          - Pro
          - Home
          - ProWorkstations
      remove_defender:
        description: 'Remove Windows Defender (applies to maker and core)'
        required: false
        default: false
        type: boolean
      remove_ai:
        description: 'Remove AI/Copilot components (applies to maker and core)'
        required: false
        default: true
        type: boolean
      remove_edge:
        description: 'Remove Microsoft Edge browser (applies to maker and core)'
        required: false
        default: true
        type: boolean
      remove_store:
        description: 'Remove Microsoft Store (applies to maker and core)'
        required: false
        default: true
        type: boolean
  push:
    branches:
      - main
    paths:
      - '*.ps1'
      - '.github/workflows/*.yml'
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 180
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup PowerShell
        shell: pwsh
        run: |
          $PSVersionTable
          Write-Host "PowerShell version: $($PSVersionTable.PSVersion)"
          
      - name: Download and Mount Windows ISO
        shell: pwsh
        env:
          ISO_URL_SECRET: ${{ secrets.ISO_URL }}
          ISO_URL_INPUT: ${{ github.event.inputs.iso_url || inputs.iso_url }}
          DEFAULT_ISO_URL: 'https://software-static.download.prss.microsoft.com/dbazure/888969d5-f34g-4e03-ac9d-1f9786c66749/26200.6584.250915-1905.25h2_ge_release_svc_refresh_CLIENT_CONSUMER_x64FRE_en-us.iso'
        run: |
          $ErrorActionPreference = 'Stop'
          
          # Determine ISO source
          # Priority: Input ISO_URL (if not empty) > Secret ISO_URL > Default URL
          $isoUrl = $null
          
          # Check if ISO_URL_INPUT is provided and not empty
          if ($env:ISO_URL_INPUT -and $env:ISO_URL_INPUT.Trim() -ne '') {
            Write-Host "Using ISO URL from workflow input..."
            $isoUrl = $env:ISO_URL_INPUT.Trim()
          } elseif ($env:ISO_URL_SECRET -and $env:ISO_URL_SECRET.Trim() -ne '') {
            Write-Host "Using ISO URL from repository secret..."
            $isoUrl = $env:ISO_URL_SECRET.Trim()
          } else {
            Write-Host "ISO URL input is empty, using default Windows 11 25H2 ISO URL..."
            $isoUrl = $env:DEFAULT_ISO_URL
          }
          
          $isoFilePath = "$env:RUNNER_TEMP\windows.iso"
          
          Write-Host "Downloading Windows ISO from: $isoUrl"
          Write-Host "This may take a while depending on your connection speed..."
          
          try {
            Invoke-WebRequest -Uri $isoUrl -OutFile $isoFilePath -UseBasicParsing
            Write-Host "✓ ISO downloaded successfully" -ForegroundColor Green
          } catch {
            Write-Error "Failed to download ISO: $_"
            exit 1
          }
          
          # Verify ISO file exists
          if (-not (Test-Path $isoFilePath)) {
            Write-Error "ISO file not found at: $isoFilePath"
            exit 1
          }
          
          $isoSize = (Get-Item $isoFilePath).Length / 1GB
          Write-Host "Downloaded ISO size: $([math]::Round($isoSize, 2)) GB"
          
          Write-Host "Mounting ISO file: $isoFilePath"
          
          # Mount ISO and get drive letter
          try {
            $mountResult = Mount-DiskImage -ImagePath $isoFilePath -PassThru -ErrorAction Stop
            $volume = $mountResult | Get-Volume
            $isoDriveLetter = $volume.DriveLetter
            
            if ($isoDriveLetter) {
              $isoDrive = "$isoDriveLetter`:"
              Write-Host "✓ ISO mounted successfully to drive: $isoDrive" -ForegroundColor Green
              echo "ISO_DRIVE=$isoDrive" >> $env:GITHUB_ENV
              echo "ISO_FILE_PATH=$isoFilePath" >> $env:GITHUB_ENV
            } else {
              Write-Error "Failed to get drive letter from mounted ISO"
              exit 1
            }
          } catch {
            Write-Error "Failed to mount ISO: $_"
            exit 1
          }
          
      - name: Build Tiny11 ISO
        shell: pwsh
        env:
          BUILD_TYPE: ${{ github.event.inputs.build_type || inputs.build_type || 'maker' }}
          VERSION_SELECTOR: ${{ github.event.inputs.version_selector || inputs.version_selector || 'Auto' }}
          REMOVE_DEFENDER: ${{ github.event.inputs.remove_defender || inputs.remove_defender || 'false' }}
          REMOVE_AI: ${{ github.event.inputs.remove_ai || inputs.remove_ai || 'true' }}
          REMOVE_EDGE: ${{ github.event.inputs.remove_edge || inputs.remove_edge || 'true' }}
          REMOVE_STORE: ${{ github.event.inputs.remove_store || inputs.remove_store || 'true' }}
        run: |
          # Set error handling - continue on non-critical errors
          $ErrorActionPreference = 'Continue'
          $script:buildFailed = $false
          $script:buildError = $null
          
          # Get ISO drive from mounted ISO
          $isoDrive = $env:ISO_DRIVE
          if (-not $isoDrive) {
            Write-Error "ISO drive not set. Mount step may have failed."
            exit 1
          }
          
          # Scratch drive will use runner temp or current directory
          $scratchDrive = $PSScriptRoot
          
          Write-Host "Building Tiny11 ISO..."
          Write-Host "ISO Drive: $isoDrive"
          Write-Host "Scratch Drive: $scratchDrive"
          Write-Host "Build Type: $env:BUILD_TYPE"
          
          # Build arguments - use hashtable for named parameters
          $buildParams = @{}
          
          # Extract drive letter (remove colon)
          if ($isoDrive -match '^([A-Z]):$') {
            $buildParams['ISO'] = $Matches[1]
          } else {
            Write-Error "Invalid ISO drive format: $isoDrive"
            exit 1
          }
          
          # Determine script to run
          $buildType = $env:BUILD_TYPE
          $scriptName = switch ($buildType) {
            'core' { 'tiny11Coremaker.ps1' }
            default { 'tiny11maker.ps1' }
          }
          
          # Add NonInteractive flag for CI/CD
          $buildParams['NonInteractive'] = $true
          
          # Add version selector
          $versionSelector = if ($env:VERSION_SELECTOR) { $env:VERSION_SELECTOR } else { 'Auto' }
          $buildParams['VersionSelector'] = $versionSelector
          Write-Host "Version selector: $versionSelector"
          
          # Helper function to convert boolean/string to yes/no
          function Convert-ToYesNo {
            param($value, $default = 'yes')
            if (-not $value) { return $default }
            $str = $value.ToString().ToLower()
            if ($str -eq 'true' -or $str -eq '1' -or $str -eq 'yes') { return 'yes' }
            return 'no'
          }
          
          # Add optional debloat parameters for all build types (maker, core)
          # All build types now honor workflow debloat settings
          Write-Host "Adding optional debloat parameters..."
          
          $buildParams['RemoveDefender'] = Convert-ToYesNo $env:REMOVE_DEFENDER 'no'
          $buildParams['RemoveAI'] = Convert-ToYesNo $env:REMOVE_AI 'yes'
          $buildParams['RemoveEdge'] = Convert-ToYesNo $env:REMOVE_EDGE 'yes'
          $buildParams['RemoveStore'] = Convert-ToYesNo $env:REMOVE_STORE 'yes'
          
          Write-Host "Debloat options ($buildType): Defender=$($buildParams['RemoveDefender']), AI=$($buildParams['RemoveAI']), Edge=$($buildParams['RemoveEdge']), Store=$($buildParams['RemoveStore'])"
          
          Write-Host "Running: $scriptName"
          Write-Host "Parameters: ISO=$($buildParams['ISO']), NonInteractive=$($buildParams['NonInteractive']), VersionSelector=$($buildParams['VersionSelector'])"
          Write-Host "  Debloat: Defender=$($buildParams['RemoveDefender']), AI=$($buildParams['RemoveAI']), Edge=$($buildParams['RemoveEdge']), Store=$($buildParams['RemoveStore'])"
          
          # Run the builder script with splatting
          # Catch errors but continue - scripts have their own error handling
          try {
            & ".\$scriptName" @buildParams 2>&1 | ForEach-Object {
              if ($_ -match "Removal failed|Warning.*Failed to remove") {
                Write-Warning $_
              } else {
                Write-Host $_
              }
            }
            
            # Check exit code
            if ($LASTEXITCODE -ne 0) {
              Write-Warning "Script exited with code $LASTEXITCODE, but continuing to check for ISO..."
            }
          } catch {
            Write-Warning "Error running script: $($_.Exception.Message)"
            $script:buildFailed = $true
            $script:buildError = $_
          }
          
          # Check if ISO was created (different names for different build types)
          $isoName = switch ($buildType) {
            'core' { 'tiny11-core.iso' }
            default { 'tiny11.iso' }
          }
          # Use repository workspace, not $PSScriptRoot (which points to a temp script path in GitHub Actions)
          $repoRoot = $env:GITHUB_WORKSPACE
          $isoPath = Join-Path $repoRoot $isoName
          
          if (Test-Path $isoPath) {
            Write-Host "\u2713 ISO created successfully: $isoPath" -ForegroundColor Green
            $isoSize = (Get-Item $isoPath).Length / 1GB
            Write-Host "ISO size: $([math]::Round($isoSize, 2)) GB"
            # Exit successfully even if there were warnings
            exit 0
          } else {
            Write-Error "ISO was not created at expected path: $isoPath"
            if ($script:buildError) {
              Write-Error "Build error: $($script:buildError.Exception.Message)"
            }
            exit 1
          }
          
      - name: Upload ISO artifact
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: ${{ github.event.inputs.build_type || inputs.build_type || 'maker' }}-iso-${{ github.run_number }}
          path: |
            tiny11.iso
            tiny11-core.iso
            *.log
          retention-days: 7
          compression-level: 0
          
      - name: Create Release
        if: github.event_name == 'release' && github.event.action == 'published'
        shell: pwsh
        run: |
          $isoPath = "tiny11.iso"
          if (Test-Path $isoPath) {
            Write-Host "Preparing release asset..."
            $isoSize = (Get-Item $isoPath).Length / 1GB
            Write-Host "ISO size: $([math]::Round($isoSize, 2)) GB"
            
            # Note: Actual release upload would be handled by release action
            # This step just prepares the file
          }
          
      - name: Cleanup
        if: always()
        shell: pwsh
        env:
          ISO_FILE_PATH: ${{ env.ISO_FILE_PATH }}
        run: |
          # Unmount ISO if we mounted it
          if ($env:ISO_FILE_PATH) {
            Write-Host "Unmounting ISO: $env:ISO_FILE_PATH"
            try {
              Get-DiskImage | Where-Object { $_.ImagePath -eq $env:ISO_FILE_PATH } | Dismount-DiskImage -ErrorAction Stop
              Write-Host "\u2713 ISO unmounted successfully" -ForegroundColor Green
            } catch {
              Write-Warning "Failed to unmount ISO: $_"
            }
            
            # Cleanup temporary ISO file if it was downloaded
            if ($env:ISO_FILE_PATH -like "*RUNNER_TEMP*") {
              Write-Host "Removing temporary ISO file..."
              Remove-Item -Path $env:ISO_FILE_PATH -Force -ErrorAction SilentlyContinue
            }
          }
