name: Test Workflow Trigger

on:
  workflow_dispatch:
    inputs:
      test_input:
        description: 'Test input'
        required: false
        default: 'test'
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test step
        run: echo "Workflow triggered successfully with input: ${{ inputs.test_input }}"

